---
- name: Install plg stack via docker
  gather_facts: yes
  hosts: "plg-gdr"
  become: yes
  roles:
  - role: plg-compose
    ansible_python_interpreter: /usr/bin/env python3
    environment:
      PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
