---
- name: Install pip
  gather_facts: True
  hosts: "plg-gdr"
  become: yes
  pre_tasks:
  - name: python installed
    package: name={{ packages }}
    vars:
      packages:
      - "{{ python_package|d('python3') }}"
#     - "{{ python_package|d('python3') }}-setuptools"
      - libselinux-{{ python_package|d('python3') }}
  roles:
  - role: bobbyrenwick.pip
    ansible_python_interpreter: "/usr/bin/env python3"
    environment:
      PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
