---
docker_edition: 'ce'
docker_version: ''
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present

old_docker:
  RedHat:
  - docker
  - docker-client
  - docker-client-latest
  - docker-common
  - docker-latest
  - docker-latest-logrotate
  - docker-logrotate
  - docker-engine
  Debian:
  - docker
  - docker-engine
  - docker.io
  - containerd
  - runc

pre_requisite:
  RedHat:
  - yum-utils
  - device-mapper-persistent-data
  - lvm2
  Debian:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

# set when REPLACE dockerd_options
dockerd_options: []
# - "--insecure-registry localhost:5000"

dockerd_environments: []
# - "http_proxy=http://example.com:8888"

dockerd_settings:
  log-driver: local

docker_plugins_args: []
# - "grafana/loki-docker-driver:latest --alias loki --grant-all-permissions"
