---

- name: Add Docker GPG key (RedHat).
  when: ansible_distribution_file_variety == "RedHat"
  rpm_key: >
    key=https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg
    state=present

- name: Add Docker repository.(RedHat)
  when: ansible_distribution_file_variety == "RedHat"
  get_url: >
    dest=/etc/yum.repos.d
    url=https://download.docker.com/linux/centos/docker-{{ docker_edition }}.repo
    mode=0644

- name: epel-release installed
  yum: name=epel-release
